/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.nstrefa.wojciechmocek;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
