version: "3.7"
services:
  dockertest:
    stdin_open: true
    container_name: IntellijDockerRemoteDebugTest
    image: dockertest:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "5005:5005"

# To debug 'dockertest' run: $ docker-compose up -d && docker attach IntellijDockerRemoteDebugTest
